<?php

namespace ContainerE3z86jQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilm2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d_Zi8_Z.App\Entity\Film' shared service.
     *
     * @return \App\Entity\Film
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.d_Zi8_Z": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".');
    }
}
