<?php

<<<<<<<< HEAD:var/cache/dev/ContainerCg4DniB/getFilm2Service.php
namespace ContainerCg4DniB;
========
namespace ContainerE3z86jQ;
>>>>>>>> panier:var/cache/dev/ContainerE3z86jQ/getFilm2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilm2Service extends App_KernelDevDebugContainer
{
    /**
<<<<<<<< HEAD:var/cache/dev/ContainerCg4DniB/getFilm2Service.php
     * Gets the private '.errored..service_locator.sUM6vBH.App\Entity\Film' shared service.
========
     * Gets the private '.errored..service_locator.d_Zi8_Z.App\Entity\Film' shared service.
>>>>>>>> panier:var/cache/dev/ContainerE3z86jQ/getFilm2Service.php
     *
     * @return \App\Entity\Film
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerCg4DniB/getFilm2Service.php
        throw new RuntimeException('Cannot autowire service ".service_locator.sUM6vBH": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".');
========
        throw new RuntimeException('Cannot autowire service ".service_locator.d_Zi8_Z": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".');
>>>>>>>> panier:var/cache/dev/ContainerE3z86jQ/getFilm2Service.php
    }
}
