<?php

namespace ContainerBchqL5d;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AvYFkEZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.avYFkEZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.avYFkEZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'SearchRepository' => ['privates', 'App\\Repository\\SearchRepository', 'getSearchRepositoryService', true],
        ], [
            'SearchRepository' => 'App\\Repository\\SearchRepository',
        ]);
    }
}
