<?php

namespace ContainerL3xXFIN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LgUBIreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lgUBIre' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lgUBIre'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'film' => ['privates', '.errored..service_locator.lgUBIre.App\\Entity\\Film', NULL, 'Cannot autowire service ".service_locator.lgUBIre": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".'],
            'filmRepository' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'film' => 'App\\Entity\\Film',
            'filmRepository' => 'App\\Repository\\FilmRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
