<?php

namespace ContainerFkxV31N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OQI_BNjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oQI.bNj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oQI.bNj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactFormHandler' => ['privates', 'App\\Form\\FormHandler\\ContactFormHandler', 'getContactFormHandlerService', true],
        ], [
            'contactFormHandler' => 'App\\Form\\FormHandler\\ContactFormHandler',
        ]);
    }
}
