<?php

namespace ContainerCrxQEkx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q1YAp8dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q1YAp8d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q1YAp8d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'SearchRepository' => ['privates', 'App\\Repository\\SearchMusiqueRepository', 'getSearchMusiqueRepositoryService', true],
        ], [
            'SearchRepository' => 'App\\Repository\\SearchMusiqueRepository',
        ]);
    }
}
