<?php

namespace ContainerCrxQEkx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1nwYuLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1nwYuL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1nwYuL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'musique' => ['privates', '.errored..service_locator.F1nwYuL.App\\Entity\\Musique', NULL, 'Cannot autowire service ".service_locator.F1nwYuL": it needs an instance of "App\\Entity\\Musique" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'musique' => 'App\\Entity\\Musique',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
