<?php

namespace ContainerF7iZ4Os;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHfGqcUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IHfGqcU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IHfGqcU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscriptionFormHandler' => ['privates', 'App\\Form\\FormHandler\\InscriptionFormHandler', 'getInscriptionFormHandlerService', true],
        ], [
            'inscriptionFormHandler' => 'App\\Form\\FormHandler\\InscriptionFormHandler',
        ]);
    }
}
