<?php

namespace ContainerP4cJChh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DZi8ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d_Zi8_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_Zi8_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'film' => ['privates', '.errored..service_locator.d_Zi8_Z.App\\Entity\\Film', NULL, 'Cannot autowire service ".service_locator.d_Zi8_Z": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".'],
        ], [
            'film' => 'App\\Entity\\Film',
        ]);
    }
}
