<?php

namespace ContainerBTxPQp0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactFormHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6uJsiNk.App\FormHandler\ContactFormHandler' shared service.
     *
     * @return \App\FormHandler\ContactFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6uJsiNk": it references class "App\\FormHandler\\ContactFormHandler" but no such service exists.');
    }
}
