<?php

namespace ContainerOpzrNWR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Kw35iEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..kw35iE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..kw35iE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'SearchRepository' => ['privates', 'App\\Repository\\SearchRepository', 'getSearchRepositoryService', true],
            'filmRepository' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService', true],
        ], [
            'SearchRepository' => 'App\\Repository\\SearchRepository',
            'filmRepository' => 'App\\Repository\\FilmRepository',
        ]);
    }
}
