<?php

namespace ContainerOpzrNWR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B46_13kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B46.13k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B46.13k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticator' => ['privates', 'App\\Security\\AppAuthenticator', 'getAppAuthenticatorService', true],
            'inscriptionFormHandler' => ['privates', 'App\\Form\\FormHandler\\InscriptionFormHandler', 'getInscriptionFormHandlerService', true],
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'mail' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
        ], [
            'authenticator' => 'App\\Security\\AppAuthenticator',
            'inscriptionFormHandler' => 'App\\Form\\FormHandler\\InscriptionFormHandler',
            'jwt' => 'App\\Service\\JWTService',
            'mail' => 'App\\Service\\SendMailService',
            'passwordHasher' => '?',
            'userAuthenticator' => '?',
        ]);
    }
}
