<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerCg4DniB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg4DniB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCg4DniB.legacy');
=======
if (\class_exists(\ContainerP4cJChh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP4cJChh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP4cJChh.legacy');
>>>>>>> panier

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerCg4DniB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCg4DniB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cg4DniB',
    'container.build_id' => 'f3fe2ef7',
    'container.build_time' => 1680310642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg4DniB');
=======
    \class_alias(\ContainerP4cJChh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP4cJChh\App_KernelDevDebugContainer([
    'container.build_hash' => 'P4cJChh',
    'container.build_id' => '61bc72d4',
    'container.build_time' => 1680359088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP4cJChh');
>>>>>>> panier
