<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU1XApYi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU1XApYi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU1XApYi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU1XApYi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU1XApYi\App_KernelDevDebugContainer([
    'container.build_hash' => 'U1XApYi',
    'container.build_id' => '972b1721',
    'container.build_time' => 1680456265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU1XApYi');
