<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDMknF4o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDMknF4o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDMknF4o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDMknF4o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDMknF4o\App_KernelDevDebugContainer([
    'container.build_hash' => 'DMknF4o',
    'container.build_id' => '9f29af0f',
    'container.build_time' => 1677147707,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDMknF4o');
